spring.application.name=demo
spring.profiles.active=dev
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.security=DEBUG
#logging.level.com.example.demo.controller=DEBUG
spring.datasource.url=jdbc:postgresql://localhost:862/spring_db
spring.datasource.username=spring_user
spring.datasource.password=spring_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# Redis
spring.data.redis.host=localhost
spring.data.redis.port=866
spring.data.redis.password=123
jwt.secret=lIvEWIuWPmX0XCUghWcQQJRil2BQoaYqh8SM2dA0xhP
jwt.expiration=86400000

