spring.application.name=demo
logging.level.com.example.demo.controller=DEBUG
spring.datasource.url=jdbc:postgresql://localhost:862/spring_db
spring.datasource.username=spring_user
spring.datasource.password=spring_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
